name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Log in to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker Image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/blog:v${{ github.run_number }} .
      
    - name: Push Docker Image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/blog:v${{ github.run_number }}
      
    - name: Build MySQL Docker Image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/mysql:v${{ github.run_number }} -f docker-database/Dockerfile .
      working-directory: .
      
    - name: Push MySQL Docker Image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/mysql:v${{ github.run_number }}
      
  modifygit:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: changing the deployment of git repo
        with:
          repository: 'bube-ristovska/app-manifest'
          token: ${{ secrets.GIT_PASSWORD }}
      - name: modify the image
        run: |
          git config user.email ristovska724@gmail.com
          git config user.name Bube
          pwd
          cat deployment.yaml
          pwd
          sed -i "s+buberistovska/blog.*+buberistovska/blog:v$RUN_NUMBER+g" deployment.yaml
          sed -i "s+buberistovska/mysql.*+buberistovska/mysql:v$RUN_NUMBER+g" deployment.yaml
          cat deployment.yaml
          git add .
          git status
          git diff
          git commit -m 'Done  by Github Actions Job changemanifest: ${{ github.run_number }}'
          git push origin main
        env:
          GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
          GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
          RUN_NUMBER: ${{ github.run_number }}

